### PR TITLE
Update types, add dialyzer mix task

### PR DESCRIPTION
**Pull request by fastjames**
In order to ensure that stated typespecs align with function behaviors,
update the typespec for Quarto.Page.Metadata to allow `nil` for cursor
values and `0` for record counts.

Add `dialyxir` to support easier execution of dialyzer.

### CODE REVIEW

**Comment by fastjames** [comment]
This one got me today, since I was writing a function to skip setting the response header if the before/after cursor was nil. According to dialyzer that's not possible. :-D

**Comment by fastjames** [comment]
Setting this to WIP since I tested it with my failing application and it did not appear to fix the dialyzer failure. I will un-WIP it once my local test case is passing.

**Comment by fastjames** [comment]
> Setting this to WIP since I tested it with my failing application and it did not appear to fix the dialyzer failure. I will un-WIP it once my local test case is passing.

All clear -- I needed to clear my PLT cache. It's passing now.

**Review by maartenvanvliet — APPROVED** [review]
Love it! Thx!

**Pull request merged**
